package com.campbuddy.`object`

import com.campbuddy.classes.Event

object Mockup {
    val names = listOf(
        "Jakub Nowak",
        "Anna Kowalska",
        "Piotr Wiśniewski",
        "Katarzyna Lewandowska",
        "Michał Wójcik",
        "Agnieszka Kamińska",
        "Tomasz Zieliński",
        "Aleksandra Szymańska",
        "Andrzej Wojciechowski",
        "Marta Kozłowska",
        "Krzysztof Jankowski",
        "Magdalena Mazur",
        "Rafał Wojciechowski",
        "Ewa Czarnecka",
        "Damian Grabowski",
        "Barbara Kwiatkowska",
        "Marcin Zając",
        "Izabela Krawczyk",
        "Grzegorz Król",
        "Agata Piotrowska",
        "Paweł Sikora",
        "Monika Dąbrowska",
        "Łukasz Marciniak",
        "Natalia Pawłowska",
        "Jacek Zalewski",
        "Joanna Kaczmarek",
        "Łukasz Michalak",
        "Justyna Zawadzka",
        "Adam Wieczorek",
        "Patrycja Jabłońska",
        "Robert Dudek",
        "Joanna Woźniak",
        "Mateusz Majewski",
        "Aneta Grabowska",
        "Maciej Nowicki",
        "Karolina Olszewska",
        "Bartosz Adamczyk",
        "Małgorzata Jaworska",
        "Dariusz Malinowski",
        "Natalia Lipińska",
        "Tadeusz Pawlik",
        "Weronika Gajewska",
        "Arturek Wichciński",
        "Anna Jędrzejczyk",
        "Sebastian Laskowski",
        "Maria Cieślak",
        "Zbigniew Duda",
        "Alicja Kowalewska",
        "Karol Ziółkowski",
        "Dorota Domańska",
        "Filip Orłowski",
        "Katarzyna Sikorska",
        "Stefan Borkowski",
        "Maja Kubicz",
        "Wojciech Stefanik",
        "Joanna Sowa",
        "Krystian Wojtas",
        "Aleksandra Baran",
        "Cezary Wróbel",
        "Martyna Włodarczyk",
        "Daniel Tomczak",
        "Izabela Ostrowska",
        "Marek Krajewski",
        "Beata Wołoszyn",
        "Józef Pietrzak",
        "Klaudia Makowska",
        "Mirosław Zalewski",
        "Beata Laskowska",
        "Łukasz Czajkowski",
        "Paulina Janik",
        "Dawid Maliszewski",
        "Adrianna Sikorska",
        "Jan Górski",
        "Paulina Przybylska",
        "Igor Kurowski",
        "Marta Bąk",
        "Piotr Sokołowski",
        "Zuzanna Nowaczyk",
        "Oskar Zaręba",
        "Ewelina Piątek",
        "Konrad Górka",
        "Kinga Walczak",
        "Jakub Stępień",
        "Sandra Lubińska",
        "Marcin Piekarski",
        "Aleksandra Wolska",
        "Gracjan Baranowski",
        "Klaudia Broż",
        "Przemysław Kruk",
        "Magda Sobczak",
        "Szymon Michalski",
        "Anita Nowakowska",
        "Maciej Serafin",
        "Joanna Dziedzic",
        "Radosław Stasiak",
        "Dominika Klimczak",
        "Krystian Chmiel",
        "Monika Piwowarska",
        "Stanisław Lichota",
        "Last Name"
    )

    val events = listOf(
        Event("7:30", "Pobudka"),
        Event("8:00", "Zbiórka na placu głównym"),
        Event("8:15", "Śniadanie"),
        Event("9:45", "Przerwa"),
        Event("10:15", "Zbiórka na placu głównym"),
        Event("11:00", "Wyjazd", "A"),
        Event("11:00", "Zajęcia", "B"),
        Event("12:30", "Przerwa", "A"),
        Event("12:30", "Zbióka", "B"),
        Event("13:30", "Zbiórka na placu głównym"),
        Event("13:45", "Obiad"),
        Event("14:15", "Czas wolny"),
    ).groupBy { it.hour }
}